rss:
  url: "https://www.soumu.go.jp/news.rdf"
gemini:
  api_key: "YOUR_API_KEY"
  max_tokens: 65535
  retry_count: 3
  retry_interval_sec: 5
  screening_model: "gemini-2.0-flash"
  screening_prompt: |
    Webページの内容を見て、要約する価値があるかどうかを判断してください。

    要約する価値のないWebページは以下のような特徴を持ちます。以下のいずれかの特徴を持つ場合、NOと判定してください。
    1. 添付資料がない、もしくはすべて非公開等で利用できない状態にある

    要約する価値のあるWebページは以下のような特徴を持ちます。この場合はYESと判定してください。
    1. 適切にフォーマットされている
    2. タイトルが前のドキュメントからの機械的な繰り返しではなく、人間が新たに書いたものだと思われる
    3. 添付資料があり、適切に添付されている

    判断を待つべきWebページは以下のような特徴を持ちます。この場合はWAITと判定してください。
    1. 添付資料が準備できておらず、後日掲載などと書かれている
    2. その他、時間経過により要約する価値のあるページになると考えられる記述が含まれる

    Webページに含まれる添付資料 {{ len .Documents }}件:
    {{ range .Documents }}
    - URL: {{ .URL }}, Size: {{ .Size }} bytes{{ end }}
  summerizing_model: "gemini-2.5-flash-preview-05-20"
  summeizing_prompt: |
    あなたは「総務省会議議事録要約ツール」です。
      1) 会議のメタ情報を含むWebページ(HTMLテキスト)
      2) 議事録や参考資料を含むPDFファイル
    を渡すため、各PDFファイルの要約を出力し、それらの内容をもとに会議全体を要約してください。

    最終要約はページのタイトルとともに表示されるため、ページのタイトルに含まれる情報は必要ありません。タイトルの内容を繰り返して文字数を消費しないように省略してください。
    例: 「令和6年度情報通信メディアの利用時間と情報行動に関する調査報告書」の公表
    総務省情報通信政策研究所は、令和6年度情報通信メディアの利用時間と情報行動に関する調査報告書を公表しました。全年代でインターネット利用時間が最も長く、…
    ↓
    総務省情報通信政策研究所が調査報告書を公表しました。全年代でインターネット利用時間が最も長く、…

    【ドキュメント要約出力形式】
    - metadata: タイトル、日時、出席者、開催場所、議題などのメタ情報
    - keyPoints: 重要な発言や決定事項を3~5項目列挙
    - summary: 文書の要点を日本語で簡潔にまとめる

    【省略可能情報出力形式】
    - omissibles: タイトルに含まれており、要約に含める必要のない情報

    【最終要約出力形式】
    - final_summary: 会議の特に重要な部分を取り上げ、ですます調、3~5文、全体で200文字程度の日本語にまとめる
mastodon:
  instance_url: "YOUR_MASTODON_INSTANCE_URL"
  access_token: "YOUR_MASTODON_ACCESS_TOKEN"
  client_id: "YOUR_MASTODON_CLIENT_ID"
  client_secret: "YOUR_MASTODON_CLIENT_SECRET"
  post_template: |
    {{ .Title }}

    {{ .Summary }}

    {{ .URL }}
storage:
  download_dir: "./mic_summary_bot/downloads"
  keep_local_copy: true
database:
  path: "./mic_summary_bot/database.sqlite"
