package micsummarybot

import (
	"context"
	"fmt"

	"google.golang.org/genai"
)

type GenAIClient struct {
	Client           *genai.Client
	MaxRetry         int
	RetryIntervalSec int
	ScreeningModel   string
	SummarizingModel string
	DownloadDir      string
	KeepLocalCopy    bool
}

// NewGenAIClient は新しいGenAIClientインスタンスを作成します。
func NewGenAIClient(gemini *GeminiConfig, storage *StorageConfig) (*GenAIClient, error) {
	client, err := genai.NewClient(context.Background(), &genai.ClientConfig{
		APIKey: gemini.APIKey,
	})
	if err != nil {
		return nil, err
	}

	return &GenAIClient{
		Client:           client,
		MaxRetry:         gemini.RetryCount,
		RetryIntervalSec: gemini.RetryIntervalSec,
		ScreeningModel:   gemini.ScreeningModel,
		SummarizingModel: gemini.SummarizingModel,
		DownloadDir:      storage.DownloadDir,
		KeepLocalCopy:    storage.KeepLocalCopy,
	}, nil
}

// validateGeneratedContent はGemini APIのレスポンスに生成されたコンテンツが含まれているか確認します。
// 安全性フィルタやトークン上限で生成が止められると、候補が空になったり候補のContentがnilになったりするため、
// 原因の調査に使えるBlockReasonやFinishReasonをエラーに含めます。
func validateGeneratedContent(resp *genai.GenerateContentResponse) error {
	if len(resp.Candidates) == 0 {
		if resp.PromptFeedback != nil {
			return fmt.Errorf("no candidates generated by Gemini API: block_reason=%s", resp.PromptFeedback.BlockReason)
		}
		return fmt.Errorf("no candidates generated by Gemini API")
	}
	candidate := resp.Candidates[0]
	if candidate.Content == nil || len(candidate.Content.Parts) == 0 {
		return fmt.Errorf("no content generated by Gemini API: finish_reason=%s", candidate.FinishReason)
	}
	return nil
}
